### ISSUE TITLE
Recovery: Over-sized image

### ISSUE THREAD

**Issue by rokibhasansagar** [PitchBlack-Recovery/android_bootable_recovery#17]
- [x] I am running an _Unofficial_ build of TWRP, built from source by me from [This Device Tree](https://github.com/rokibhasansagar/android_device_twrp_WALTON_Primo_RX5/tree/pbrp-test)

**Device codename**: Primo_RX5
**TWRP version**: 3.2.3-PB-v2.9.0

#### WHAT IS THE PROBLEM?
When building the Recovery from Latest Source, the resulting Image size is around _19MB_
But many device has _maximum recovery partition size_ of _16MB_ (0x1000000) only

The _excess size_ of image can be reduced by Moving the extra Themes into /sdcard/PBRP/themes/ui.zip and Load them from there

**Comment by rezaadi0105** [comment]
Try with pb go branch https://github.com/PitchBlack-Recovery/android_bootable_recovery/tree/pb-go

**Comment by AndroiableDroid** [comment]
@rezaadi0105 Bro PBRP go is merged with PBRP branch

**Comment by rokibhasansagar** [comment]
Okay.
I'll try.

**Comment by rokibhasansagar** [comment]
This works, Thanks.

But It would be nice if we could choose from all the themes to customize, not only two; like the older PB-2.7.x version.
Please consider this as a **feature request** 🙏

**Comment by rezaadi0105** [comment]
I think recommended change device with partition recovery big, this will many theme include...because for modern theme recovery not ui.zip ..but use cmd for change theme of recovery
