### ISSUE TITLE
Gui: Themes

### ISSUE THREAD

**Issue by manjotsidhu** [PitchBlack-Recovery/android_bootable_recovery#8]
Themes are now full of device specific bugs due to different resolutions, we need to fix ->

- [x]  Theme resolution fit for every hdpi device **ASAP!**

- [x]  And we need a **New** lockscreen, the old one looks awful

**Comment by AndroiableDroid** [comment]
Yaa we need to fix buttons alignment as others are ok

**Comment by manjotsidhu** [comment]
@AndroiableDroid

**Comment by RajeshRajout** [comment]
Am testing this recovery on My Redmi Note 5 pro.
And faced one problem this recovery. If I flashed the MIUI China ROM which doesn't have the Google Apps. The ROM boots successfully.

But,  when I flash the MIUI GLobal version which comes with the  Google Apps. The ROM stuck on the Black Screen before the Google Sign in Configuration page. 

And followed the same method on Official Recovery. The ROM boots fine and Google Setup page appears and work perfectly.

**Comment by manjotsidhu** [comment]
![photo_2018-06-29_17-37-18](https://user-images.githubusercontent.com/22657113/42091482-2a928404-7bc3-11e8-83d4-3bf9c50d31be.jpg)
Background is not fitting all resoltions well 
the above device is 480 x 800

**Comment by manjotsidhu** [comment]
@RajeshRajout just make a new issue of it in this repo ...

**Comment by RajeshRajout** [comment]
@manjotsidhu Sorry am new to GitHub...

**Comment by AndroiableDroid** [comment]
all these issues are fixed now

**Comment by manjotsidhu** [comment]
@AndroiableDroid @ANDROIABLEDROID Kul 👍
