### ISSUE TITLE
Problem While Flashing Global ROMS 

### ISSUE THREAD

**Issue by RajeshRajout** [PitchBlack-Recovery/android_bootable_recovery#9]
Am testing this recovery on My Redmi Note 5 pro.
And facing one problem with this recovery. If I flashed the MIUI China ROM which doesn't have the Google Apps. The ROM boots successfully.

But, when I flash the MIUI Global version which comes with the Google Apps. The ROM stuck on the Black Screen before the Google Sign in Configuration page.

And followed the same method on Official Recovery. The ROM boots fine and Google Setup page appears and work perfectly.

**Comment by AndroiableDroid** [comment]
fixation going on

**Comment by AndroiableDroid** [comment]
fixed now
